services:
  server:
 env_file: .env
    environment:
      DB_HOST: bia-eb-alb.ctcq4u628ebj.us-east-1.rds.amazonaws.com
      DB_PORT: "5432"
      DB_PWD: fNILy8YfTHQF4ZHqxVYb
      DB_SSL__REJECT_UNAUTHORIZED: "false"
      DB_USER: postgres
      WEBSOCKETS_ENABLED: "true"
    image: /bia:568ba24_2024-04-18
    ports:
    - mode: ingress
      target: 8080
      published: "80"
      protocol: tcp
