version: "3.8"
services:
  server:
    image: ${ECR_ID1}/bia:${TAG}
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: postgres
      DB_PORT: 5432
      DB_HOST: database
      DB_SSL__REJECT_UNAUTHORIZED: false
      WEBSOCKETS_ENABLED: true