version: "3.8"
services:
  server:
    image: ${ECR_ID1}/bia:${TAG}
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: 9e0KW6z4ppaFNLHApTew
      DB_PORT: 5432
      DB_HOST: bia.ctcq4u628ebj.us-east-1.rds.amazonaws.com
      DB_SSL__REJECT_UNAUTHORIZED: false
      WEBSOCKETS_ENABLED: true